on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
      - name: Install Bundler 2.4.22
        run: gem install bundler -v 2.4.22
      - name: Install Dependencies
        run: bundle _2.4.22_ install
      - name: Debug
        run: |
          ruby -v
          bundler -v
          ls -l script/bootstrap
      - name: Run Test
        run: script/cibuild
